- .github/workflows/main.yml
> chore: update comment bot

- .gitignore
- electron/main.ts
- electron/updater.ts
- package-lock.json
- package.json
- src/App.tsx
- src/VersionSelector.tsx
Fix decentraland/unity-renderer#944
1. Download the launcher
2. Check if you can choose a branch version (select renderer branch `chore/update-version`)
> feat: version selector

- .github/workflows/main.yml
- README.md
> chore: markdown fixes

- electron/main.ts
- electron/updater.ts
- package.json
Set renderer version to the kernel
Example: ![image](https://user-images.githubusercontent.com/12563266/140411873-4e0b33d9-7aca-48ee-a5f8-e71dfe3a1268.png)
> feat: set renderer version to the kernel from electron

- electron/main.ts
- package.json
feat: allow installer to choose directory, and delete app data on uninstall
> fix: add BETA name to the launcher

- package.json
- public/index.html
Related to: decentraland/unity-renderer#1642
Center vertically the loading screen
> fix: center vertically the loading screen

- electron/main.ts
- package.json
Related to: decentraland/unity-renderer#1642
New minimum size for the window
> feat: new window size including border size

- electron/main.ts
- public/index.html
Fix decentraland/unity-renderer#1374
> feat: launcher start menu for developer mode

- electron/main.ts
Reloads Base URL to avoid remembering user position when exiting the renderer
Fixes https://github.com/decentraland/unity-renderer/issues/1457
> fix: url reload on application exit

- electron/main.ts
- package.json
> feat: allow self-signed certificate and use websocket with ssl

- electron/main.ts
- electron/updater.ts
- package.json
> fix: set config correctly in developer mode

- electron/main.ts
- electron/updater.ts
- package.json
Fix https://github.com/decentraland/unity-renderer/issues/1260
> feat: custom protocol

- electron/cmdParser.ts
- electron/helpers.ts
- electron/main.ts
- electron/types.ts
- electron/updater.ts
- electron/window.ts
- package.json
Maintenance refactor
Fix https://github.com/decentraland/unity-renderer/issues/1841
> refactor: split code

- .github/workflows/build.yml
- electron/main.ts
- electron/window.ts
- package.json
Fix https://github.com/decentraland/unity-renderer/issues/1894
> fix: incorrect parse of custom protocol

- electron/main.ts
- electron/updater.ts
- electron/window.ts
- package.json
fix: remove double quotes opening the executable in Mac
fix: removed the auto updater in Mac
refactor: format code
> fix: disable background throttling and more

- package.json
> chore: only sign sha256, and use ts.ssl.com timestamp

- electron/installer.nsh
- package-lock.json
- package.json
Fix https://github.com/decentraland/unity-renderer/issues/1762
> feat: ask if the user wants to clear the local data on uninstall

- electron/window.ts
- package.json
> feat: don't show the launcher while is hidden in the tray

- electron/updater.ts
Add preview condition to execute rollout script
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> feat: skip setting rollout if it's in preview mode

- electron/window.ts
> fix: add ampersand to the end

- .github/dependabot.yml
- electron/window.ts
- package-lock.json
- package.json
Fix decentraland/explorer-desktop#213
> chore: update electron to last version and update other packages

- electron/main.ts
- electron/updater.ts
- electron/window.ts
- package.json
- public/index.html
> fix: handle the close of the renderer correctly

- electron/updater.ts
- package.json
Since we updated to the last Electron version, now the folders are not auto-created.
> fix: create folders needed

- electron/updater.ts
- package.json
> fix: new unzipper doesn't forward executable file permissions on mac

- electron/updater.ts
> refactor: change exec to execFile

- electron/updater.ts
- package.json
> fix: check if executable no exists and report that error

- electron/main.ts
- electron/types.ts
- electron/updater.ts
- electron/window.ts
- package-lock.json
- package.json
Related to https://github.com/decentraland/explorer-desktop/issues/174
> feat: add rollout

- .github/workflows/main.yml
- README.md
- package.json
- scripts/prepare-artifacts.js
Part of decentraland/explorer-desktop#184
> feat: add AppX build

- package.json
> chore: change publisher name

- README.md
- electron/cmdParser.ts
- electron/helpers.ts
- electron/main.ts
- electron/types.ts
- electron/updater.ts
- electron/window.ts
Fix https://github.com/decentraland/explorer-desktop/issues/303
> feat: add custom parameter to choose the desktop version

- .github/workflows/build.yml
- package.json
- scripts/prepare-artifacts.js
> chore: build appx in another ci step

- .github/workflows/build.yml
> chore: fix upload artifacts on main

- electron/helpers.ts
- electron/main.ts
- electron/rollbar.ts
- package-lock.json
- package.json
Adds rollbar integration and crash memory dump generation, they will be generated under: 
Windows: `%LOCALAPPDATA%/DecentralandLauncher` 
Unix: `/Users/${USER}/Library/Application Support/DecentralandLauncher`
Solves #65 
> feat: rollbar integration

- electron/main.ts
- electron/window.ts
> fix: swap newVersion and installedVersion

- electron/updater.ts
...
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> fix error reporting

- package.json
...
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> release: 0.1.49

- electron/helpers.ts
- package.json
Removing BETA label from the titles https://github.com/decentraland/unity-renderer/issues/3795
...
1. Open a launcher
2. Check if title of the window does not have BETA in the name.
> chore: removing bata label from the title

- .github/workflows/build.yml
This PR allows dependabot to run without failing
> chore: prevent upload step for failing

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- electron/main.ts
- electron/updater.ts
- electron/window.ts
- package.json
- public/index.html
...
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> fix: url redirect not working

- .github/workflows/build.yml
...
1. Go to: https://decentraland.zone/play/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> chore: add workflow_dispatch trigger

- package.json
...
1. Go to: https://decentraland.zone/play/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> chore: bump version to 0.1.56

- .github/workflows/build.yml
...
1. Go to: https://decentraland.zone/play/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...
> fix: add signing method v2 to windows build esigner
